// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtjQgXJlzxG_e-br8tX5-F6v9e7C0I9Y0',
    appId: '1:1081466467044:web:2a961178cd09f8dfbcf2f1',
    messagingSenderId: '1081466467044',
    projectId: 'bmi-tracker-app',
    authDomain: 'bmi-tracker-app.firebaseapp.com',
    storageBucket: 'bmi-tracker-app.appspot.com',
    measurementId: 'G-XDBXSTFXH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ0pxN9X3RT7KuqVKBq_sP-juMRqUBXbw',
    appId: '1:1081466467044:android:784b660e6f9db13bbcf2f1',
    messagingSenderId: '1081466467044',
    projectId: 'bmi-tracker-app',
    storageBucket: 'bmi-tracker-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3e0nVeFtf1dLmUbtGzfR_mAxNCTWc7Ns',
    appId: '1:1081466467044:ios:67db32dbdbb3bf37bcf2f1',
    messagingSenderId: '1081466467044',
    projectId: 'bmi-tracker-app',
    storageBucket: 'bmi-tracker-app.appspot.com',
    iosBundleId: 'com.abdalla.bmiTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3e0nVeFtf1dLmUbtGzfR_mAxNCTWc7Ns',
    appId: '1:1081466467044:ios:67db32dbdbb3bf37bcf2f1',
    messagingSenderId: '1081466467044',
    projectId: 'bmi-tracker-app',
    storageBucket: 'bmi-tracker-app.appspot.com',
    iosBundleId: 'com.abdalla.bmiTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtjQgXJlzxG_e-br8tX5-F6v9e7C0I9Y0',
    appId: '1:1081466467044:web:41c82f91a72b0f57bcf2f1',
    messagingSenderId: '1081466467044',
    projectId: 'bmi-tracker-app',
    authDomain: 'bmi-tracker-app.firebaseapp.com',
    storageBucket: 'bmi-tracker-app.appspot.com',
    measurementId: 'G-5GVBM02YS8',
  );
}
